# Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy Python app to Azure Web App - forwardairqna2

on:
  push:
    branches:
      - main  # 🔁 Changed from 'master' to 'main' (ensure this matches your branch)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # ✅ Use a stable version (3.13 may break builds)

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip application for deployment
        run: |
          zip -r release.zip . -x "venv/*" ".git/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Extract artifact
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EFCE528D386F4A2FB796B3F91EDC0F51 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_523274F8EC9345F18ED157D324A1F8C7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_55AA1E8E2E654807A855FFD9406E5F72 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'forwardairqna2'         # ✅ Exact name from Azure
          slot-name: 'production'            # 🔁 Lowercase 'production' is preferred
          package: .
